### PR TITLE
fix: CRDs are not included in the generated Helm tar file

### LINKED ISSUE #1336: CRDs are not included in the generated Helm tar file
As originally reported in https://github.com/quarkiverse/quarkus-operator-sdk/issues/1260#issuecomment-4221328670.

### PR DESCRIPTION
**Pull request by xstefank**
Fixes #1336

### CODE REVIEW

File: helm/deployment/src/main/java/io/quarkiverse/operatorsdk/helm/deployment/HelmAugmentationProcessor.java [hunk 1]
```diff
@@ -10,29 +8,24 @@
...
-import io.quarkus.deployment.annotations.Produce;
-import io.quarkus.deployment.pkg.builditem.ArtifactResultBuildItem;
-import io.quarkus.deployment.pkg.builditem.OutputTargetBuildItem;
 import io.quarkus.kubernetes.spi.KubernetesClusterRoleBindingBuildItem;
 import io.quarkus.qute.Qute;
 
 /**
- * This processor copies the generated CRDs into the Helm chart output directories.
+ * This processor copies the generated CRDs into the Helm chart before the Helm chart
+ * and optional tar file are generated. This ensures CRDs are included in the tar file when
```
Comment (cmoulliard) [inline helm/deployment/src/main/java/io/quarkiverse/operatorsdk/helm/deployment/HelmAugmentationProcessor.java]: I would like to suggest as wording here: "This processor copies the generated CRDs into the Helm chart tar file when the {@code quarkus.helm.create-tar-file=true} is set"

File: samples/exposedapp/src/test/java/io/halkyon/HelmTarContentIT.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
+import org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream;
+import org.junit.jupiter.api.Test;
+
+class HelmTarContentIT {
+
+    @Test
+    void helmTarContainsCRD() throws IOException {
+        Path tarFile = Files.walk(Path.of("target/helm/kubernetes"))
```
Comment (cmoulliard) [inline samples/exposedapp/src/test/java/io/halkyon/HelmTarContentIT.java:18]: How is such a tar and helm chart generated as the property `quarkus.helm.create-tar-file` is not set to `true` ?

Comment (xstefank) [reply samples/exposedapp/src/test/java/io/halkyon/HelmTarContentIT.java:18]: it is https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/samples/exposedapp/src/main/resources/application.properties#L22

Comment (cmoulliard) [reply samples/exposedapp/src/test/java/io/halkyon/HelmTarContentIT.java:18]: So the value is set to `true` by default.

File: helm/deployment/src/main/java/io/quarkiverse/operatorsdk/helm/deployment/HelmAugmentationProcessor.java (hunk 1 above)
Comment (cmoulliard) [reply helm/deployment/src/main/java/io/quarkiverse/operatorsdk/helm/deployment/HelmAugmentationProcessor.java]: Fixed with last commit

**Comment by cmoulliard** [comment]
LGTM => approved

**Review by metacosm — APPROVED** [review]
