### PR TITLE
fix: ignore okhttp3 jandex warnings for gradle builds

### LINKED ISSUE #936: Warning: [vertx, okhttp3, okio] Classes not in Jandex index
I see the following build warning:

maven:
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- io.vertx.core.Vertx (source: <unknown>)
	- io.vertx.core.http.HttpClient (source: <unknown>)
	- io.vertx.core.http.WebSocket (source: <unknown>)
	- io.vertx.core.net.ProxyType (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

gradle:
```
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- io.vertx.core.Vertx (source: <unknown>)
	- io.vertx.core.http.HttpClient (source: <unknown>)
	- io.vertx.core.http.WebSocket (source: <unknown>)
	- io.vertx.core.net.ProxyType (source: <unknown>)
	- okhttp3.OkHttpClient (source: <unknown>)
	- okhttp3.OkHttpClient$Builder (source: <unknown>)
	- okhttp3.Request$Builder (source: <unknown>)
	- okhttp3.WebSocket (source: <unknown>)
	- okio.BufferedSource (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```
I can reproduce this just by creating a [starter project](https://code.quarkus.io) that includes `quarkus-operator-sdk` and adding this file in src/main/java/MyDependentResource.java:

```
import io.fabric8.kubernetes.api.model.Service;
import io.fabric8.kubernetes.api.model.apps.Deployment;
import io.javaoperatorsdk.operator.api.reconciler.Context;
import io.javaoperatorsdk.operator.api.reconciler.EventSourceContext;
import io.javaoperatorsdk.operator.api.reconciler.ResourceDiscriminator;
import io.javaoperatorsdk.operator.processing.dependent.kubernetes.KubernetesDependent;
import io.javaoperatorsdk.operator.processing.dependent.kubernetes.KubernetesDependentResource;
import java.util.Optional;

@KubernetesDependent
public class MyDependentResource extends KubernetesDependentResource<Service, Deployment> implements ResourceDiscriminator<Service, Deployment> {
    EventSourceContext<Deployment> eventSourceContext;

    public MyDependentResource() {
        super(Service.class);
    }

    @Override
    public Optional<Service> distinguish(Class<Service> resource, Deployment primary, Context<Deployment> context) {
        return null;
    }
}
```

### PR DESCRIPTION
**Pull request by xstefank**
Fixes #936 for gradle

### CODE REVIEW

File: core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java [hunk 1]
```diff
@@ -283,6 +283,21 @@ void ignoreNonIndexedClassesWarningsInReflectiveHierarchy(
         reflectiveHierarchyIgnoreWarningBuildItemBuildProducer.produce(
                 new ReflectiveHierarchyIgnoreWarningBuildItem(
                         DotName.createSimple(io.vertx.core.net.ProxyType.class.getName())));
+        reflectiveHierarchyIgnoreWarningBuildItemBuildProducer.produce(
+                new ReflectiveHierarchyIgnoreWarningBuildItem(
+                        DotName.createSimple("okhttp3.OkHttpClient")));
```
Comment (xstefank) [inline core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java:288]: @metacosm I don't think this would be worth adding okhttp3 dependency, so I opted to list them as strings.

**Review by metacosm — APPROVED** [review]
